# Generated by Django 5.1.4 on 2024-12-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('reportado_por', models.CharField(max_length=100)),
                ('tipo_incidente', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(blank=True, max_length=30)),
                ('responsable', models.CharField(blank=True, max_length=30)),
                ('fecha_solucion', models.DateTimeField(blank=True, null=True)),
                ('acciones_realizadas', models.TextField(blank=True)),
                ('resultado', models.CharField(blank=True, max_length=100)),
                ('revisado_por', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
